### ISSUE TITLE
Article Idea:  Blockchain Based Lease Agreement Management Tool on Fuel Network

### ISSUE THREAD

**Issue by RandulaKoralage** [fuel-champions/technical-writing-bounty#8]
### Article Title

Blockchain Based Lease Agreement Management Tool on Fuel Network

### Article Summary

Lease agreements are a vital part of the real estate industry. This article demonstrates how to develop a Lease Agreement Management tool on the Fuel network using Sway and Angular. This will guide readers through the basics of developing tools within the real estate domain.

### Relevance to Fuel

The project will be developed using Sway, Fuel TypeScript SDK, and Wallet SDK, and will describe the usage of features applicable for developing solutions for real-world applications. Additionally, there is a lack of examples available online using Sway with Angular. Hence, Angular-based developers will also benefit from the application of TypeScript SDK and Wallet SDK.

### Current Project

I have been exploring the Fuel network and Sway, along with their TypeScript plugins, for the past few weeks. This exploration led me to conceive the idea of the above project. The contract will enable landlords and tenants to effortlessly create, view, and manage lease agreements. Additionally, it will integrate payment functionality into the smart contract, empowering tenants to make rent payments directly through the blockchain.

### Fuel Developer Champion Status

Yes

### Understanding of Requirements

- [X] I have read and understood the requirements for the Technical Writing Bounty.

### Payment Agreement

- [X] I understand that if my article is accepted and published, I will be paid via the Request platform.

**Comment by hummusonrails** [comment]
Hi @RandulaKoralage,

Thank you for submitting this topic idea for an article! The topic has been **approved**. The next step is to submit a draft by following the instructions [here](https://github.com/fuel-champions/technical-writing-bounty/tree/main/drafts). 

Once our team works with you on the draft, and it's published, we'll submit for payment the 500 USDC to you.

Good luck!

Ben

**Comment by RandulaKoralage** [comment]
Hi, @hummusonrails 
Is there any possibility of having an additional week for the draft?

**Comment by hummusonrails** [comment]
@RandulaKoralage Of course!

**Comment by RandulaKoralage** [comment]
@hummusonrails I will try my best to submit the draft on time. I get time only on weekends. That's why.

Any way I would like to ask, what are the things that I need to place inside the folder?

> Create a new folder in the drafts directory with the title of your article.
> Add your draft to the new folder.

I have my code (frontend+contract) and the tutorial pages I prepared to describe the project.

**Comment by RandulaKoralage** [comment]
Initial Draft submitted
