### ISSUE TITLE
Article Idea: Predicates & Their Real World Usecases #1: Identity Verification

### ISSUE THREAD

**Issue by siloeddev** [fuel-champions/technical-writing-bounty#9]
### Article Title

Predicates & Real World Usecases # 1: Identity Verification

### Article Summary

I want to demonstrate how to use a predicate to verify a signature generated by an Ethereum address.

### Relevance to Fuel

This article will demonstrate the practical implementation of predicates, which are primitives unique to Fuel and Sway.

### Current Project

No.

### Fuel Developer Champion Status

No

### Understanding of Requirements

- [X] I have read and understood the requirements for the Technical Writing Bounty.

### Payment Agreement

- [X] I understand that if my article is accepted and published, I will be paid via the Request platform.

**Comment by siloeddev** [comment]
Hi, I was just checking on other issues that are there, and they have a lot of details. In comparison, my issue seems very insufficient in details, but I have added the main points and what I want to achieve. If you guys need more details, let me know. I would be happy to elaborate on it.

I read about Fuel Developer Champions, but I am not one, so I am not sure if this is a requirement for this bounty. However, I hope that is not an issue.

**Comment by siloeddev** [comment]
Hi @hummusonrails, I wanted to follow up to see if you had a chance to review this idea and what you think about it?

**Comment by hummusonrails** [comment]
Hi @siloeddev,

Thanks for following up!

The first step is to apply to join the Champions program. You can see the details here: https://github.com/fuel-champions/pro-applications.

It's a relatively quick process. Once you are admitted, then you are welcome to submit (or have this current submission) and be considered for the bounty!

All the best,

Ben

**Comment by siloeddev** [comment]
@hummusonrails I have created issue to apply for Champions program. Let me know if anything else is needed. Here is the issue: [[Application] : Siloed Dev](https://github.com/fuel-champions/pro-applications/issues/69)
